stages:
  - build
  - test

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_TLS_CERTDIR: ""

default:
  image: docker:29.5.3-cli
  services:
    - docker:29.5.3-dind


build-image:
  tags:
    - laptop-dc
  stage: build
  script:
    - IMAGE_TAG=$(date +%Y-%m-%d-%H-%M)
    - echo "Версия сборки — $IMAGE_TAG"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG .
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
    - docker tag $CI_REGISTRY_IMAGE:$IMAGE_TAG $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest

test-image:
  tags:
    - laptop-dc
  stage: test
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker run --rm $CI_REGISTRY_IMAGE:latest
    - curl http://localhost:80